version: '3.8'

services:
  database:
    container_name: database_work
    image: mariadb:10.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workflow
      MYSQL_USER: workflow
      MYSQL_PASSWORD: workflow
    ports:
      - '3301:3306'
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql:/var/lib/mysql
  php:
    container_name: php_work
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/src
    depends_on:
      - database
  nginx:
    container_name: nginx_workflow
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
